### ISSUE TITLE
some class completions dont work at all!

### ISSUE THREAD

**Issue by siduck** [xna00/unocss-language-server#1]
this works 
![image](https://user-images.githubusercontent.com/59060246/209630723-cf99ec8b-7c73-48b3-a21d-0fa956418b42.png)

this doesnt work

![image](https://user-images.githubusercontent.com/59060246/209630677-1f601a11-f2e7-4c4b-ae65-1f09ed948d03.png)
![image](https://user-images.githubusercontent.com/59060246/209630772-06349b80-000c-4f4b-a9a6-503d26ea0051.png)

and many other classes like `bg-red-2` and so on.

**Comment by siduck** [comment]
any idea? @xna00

**Comment by siduck** [comment]
https://user-images.githubusercontent.com/59060246/209640906-1ef8713a-c56d-4668-9a89-8802296a0aed.mp4


it works weirdly, the completions regenerate when i quit insert mode

**Comment by xna00** [comment]
if you are using [nvim-cmp](https://github.com/hrsh7th/nvim-cmp), you can add `trigger_characters`.
`sources = { { name = 'nvim_lsp', trigger_characters = {'-'} }, { name = 'luasnip' } }`

**Comment by siduck** [comment]
> if you are using [nvim-cmp](https://github.com/hrsh7th/nvim-cmp), you can add `trigger_characters`. `sources = { { name = 'nvim_lsp', trigger_characters = {'-'} }, { name = 'luasnip' } }`

thanks for the quick reply, btw tailwindcss didnt needed this, is it normal to force this behaviour specifically for this lsp?

**Comment by xna00** [comment]
The code completion is provided by `@unocss/autocomplete`. This is its feature.

**Comment by siduck** [comment]
> The code completion is provided by `@unocss/autocomplete`. This is its feature.

oh got it, thanks for the help
