### ISSUE TITLE
feat(nvim-lspconfig): add it to lspconfg

### ISSUE THREAD

**Issue by zirbest** [xna00/unocss-language-server#2]
Is the LSP ready to add it to [nvim-lspconfig](https://github.com/neovim/nvim-lspconfig) ?

**Comment by xna00** [comment]
Yes.

**Comment by siduck** [comment]
writing here as i'd be reminded when it gets added

**Comment by xna00** [comment]
I have created a [PR](https://github.com/neovim/nvim-lspconfig/pull/2414).

**Comment by bobbyrahmanda13** [comment]
will this update? or will it be abandoned?

**Comment by xna00** [comment]
> I have created a [PR](https://github.com/neovim/nvim-lspconfig/pull/2414).

It has been merged.
